### ISSUE TITLE
fastapi 0.65.0 

### ISSUE THREAD

**Issue by Wiserfunding-CTO** [tomasvotava/fastapi-sso#1]
Thanks for this library. There's a new release of fasapi when you have a moment to update pyproject.toml
 
 Because no versions of fastapi-sso match >0.2.3,<0.2.4 || >0.2.4,<0.2.5 || >0.2.5,<0.2.6 || >0.2.6,<0.3.0
   and fastapi-sso (0.2.3) depends on fastapi (>=0.63.0,<0.64.0), fastapi-sso (>=0.2.3,<0.2.4 || >0.2.4,<0.2.5 || >0.2.5,<0.2.6 || >0.2.6,<0.3.0) requires fastapi (>=0.63.0,<0.64.0).
  And because fastapi-sso (0.2.4) depends on fastapi (>=0.63.0,<0.64.0), fastapi-sso (>=0.2.3,<0.2.5 || >0.2.5,<0.2.6 || >0.2.6,<0.3.0) requires fastapi (>=0.63.0,<0.64.0).
  And because fastapi-sso (0.2.5) depends on fastapi (>=0.63.0,<0.64.0)
   and fastapi-sso (0.2.6) depends on fastapi (>=0.63.0,<0.64.0), fastapi-sso (>=0.2.3,<0.3.0) requires fastapi (>=0.63.0,<0.64.0).
  So, because app depends on both fastapi (^0.65.0) and fastapi-sso (^0.2.3), version solving failed.

**Comment by tomasvotava** [comment]
@Wiserfunding-CTO thanks a lot for a heads up, I updated the `pyproject.toml` to be less picky about dependency versions. You may install `fastapi-sso==0.2.7` to bump your `fastapi` to `0.65.1`.
