### ISSUE TITLE
How to add specific scope (Api endpoint/permission) and adding Tenant id in authorization_endpoint,token_endpoint

### ISSUE THREAD

**Issue by ajaygb01** [tomasvotava/fastapi-sso#10]
![image](https://user-images.githubusercontent.com/79222710/143259336-f2cf3ea3-4b21-4037-be2a-eb3d992bb073.png)

Added screenshot.
can we add Scope and tenant values while initializing MicrosoftSSO

**Comment by tomasvotava** [comment]
Hi @ajaygb01 and thanks for bringing this up.

I agree this should be supported. If you want to work around this before I get to actually implementing this, you can always subclass the SSO provider, your solution may be:

```python
class MicrosoftCustomSSO(MicrosoftSSO):
    scope = ["<your scopes">]

    @classmethod
    async def get_discovery_document(cls) -> Dict[str, str]:
        """Get document containing api urls"""
        document = await super().get_discovery_document()
        document.update({"authorization_endpoint": "<your endpoint>"})
        return document
```

Please note that I omitted imports for brevity and also I didn't actually run this, so let me know please if there are any typos and whether this is a solution for you (at least for now).

**Comment by tomasvotava** [comment]
This was dealth with in #13
