### ISSUE TITLE
Opened discussions

### ISSUE THREAD

**Issue by parfeniukink** [tomasvotava/fastapi-sso#107]
Hey @tomasvotava.
What do you think about using Github Discussions?

Probably, I'll spend some time here in a near future since I started working closer with socials SSO and other features.
I just wanna be sure that we could have opened discussions here.

https://github.com/features/discussions

**Comment by tomasvotava** [comment]
Hey @parfeniukink, I don't know if there are a lot of users of `fastapi-sso`, but it's a good opportunity for me to try this feature, thanks :) #108
