### ISSUE TITLE
Make redirect_uri late-bound (relative to current request) in get_login_url and get_login_redirect

### ISSUE THREAD

**Issue by sammck** [tomasvotava/fastapi-sso#11]
Often, the base URL for the server is not known until after the server is started. For example, while debugging, the server might run on http://localhost:8000, while in production it might run on https://mydomain.com.  Often the server runs behind a proxy so that the actual server root URL is not even known until a request is received and it is pulled from HTTP request Host header. It's possible to delay instantiation of SSOBase until the base URL is known, and it is possible to change SSOBase.redirect_uri after it is instantiated, but both of these solutions are a little ugly. It would be nice if it were allowable to provide a site-relative URI for redirect_uri, in which case it would be evaluated relative to the current request URI at get_login_redirect() time.

Alternatively, and simpler to explain: allow redirect_uri to be overridden with a parameter at get_login_url() or get_login_redirect() time. That would allow code like:

```python
@app.get("/webauth/google/login")
async def google_login(request: Request):
    return await google_sso.get_login_redirect(redirect_uri=request.url_for("google_callback"))

@app.get("/webauth/google/callback")
async def google_callback(request: Request):
    user = await google_sso.verify_and_process(request)
    return {
        "id": user.id,
        "picture": user.picture,
        "display_name": user.display_name,
        "email": user.email,
        "provider": user.provider,
    }
```

Happy to provide a PR if it's interesting to you...

**Comment by sammck** [comment]
Happy to provide a PR if it's interesting to you...

**Comment by tomasvotava** [comment]
Hi @sammck and thanks a lot for this issue. It would be awesome if you could provide a PR as I am currently and still really busy with my primary work. I'd be happy to review it, test it and merge, though.
