### ISSUE TITLE
Pylint added as a runtime dependency

### ISSUE THREAD

**Issue by cknv** [tomasvotava/fastapi-sso#129]
Trying to upgrade to version `0.11.0` adds `pylint` (and its dependencies) to my runtime dependencies.

It seems that it got added to the `pyproject.toml` file in #118, specifically in commit b222100.

As far as I can tell, it does not seem relevant for the feature itself, and might have been added by mistake.
But I might be mistaken as I am not very familiar with either of `poetry` or `pyproject.toml`.

Is it possible to remove it from the dependencies?

**Comment by tomasvotava** [comment]
Hi @cknv, thanks for noticing! This should be resolved in 0.12.1 https://github.com/tomasvotava/fastapi-sso/releases/tag/0.12.1
