### ISSUE TITLE
support twitter

### ISSUE THREAD

**Issue by coolsnake** [tomasvotava/fastapi-sso#136]
This project is very good. I am wondering whether it can support login via twitter?

**Comment by tomasvotava** [comment]
Hi, I just requested access to Twitter API, I'll try to add Twitter support asap.

Thanks for using the project and for the enhancement idea as well.

**Comment by tomasvotava** [comment]
Try 0.13.0, hope it works well, please do not hesitate to open a new issue if anything's wrong https://github.com/tomasvotava/fastapi-sso/releases/tag/0.13.0
