### ISSUE TITLE
Possible typo in Documentation

### ISSUE THREAD

**Issue by libera826** [tomasvotava/fastapi-sso#155]
In the [use-with-fastapi-security](https://tomasvotava.github.io/fastapi-sso/how-to-guides/use-with-fastapi-security/
) guide, 
it is implemented to redirect to `url="/prot"` in the `/auth/logout/` endpoint function,
If the intention is to show that access to pages that require authentication fails after logging out, shouldn't it be redirected to `url="/protected"`?

```
@app.get("/auth/logout")
async def logout():
    """Forget the user's session."""
    response = RedirectResponse(url="/prot")
    response.delete_cookie(key="token")
    return response
```

**Comment by tomasvotava** [comment]
Hi @libera826! Thanks for that, that's a good catch, it will be fun to try git blame and see who did it. It was me, already know it was me. 😁 I'll fix it in a minute.
