### ISSUE TITLE
use fastapi-sso with external providers

### ISSUE THREAD

**Issue by tapajyotideb** [tomasvotava/fastapi-sso#20]
I am wondering if this package can be used used organizational sso & also with mock-oidc server(quay.io/appvia/mock-oidc-user-server). If so, could you please provide an example how to do that. I am unable to make it out at the moment.

**Comment by tomasvotava** [comment]
Hi @tapajyotideb, thanks for reaching out!

I have just released a 0.6.2 version of `fastapi-sso`. It contains a convenient class factory, that will help you generate the class you need without having to override the base class.

See [docs](https://tomasvotava.github.io/fastapi-sso/sso/generic.html) and [example](https://github.com/tomasvotava/fastapi-sso/blob/master/examples/generic.py).

Run following command to start the mock oidc server:

```console
docker run \
    -p 9090:9090 \
    -e PORT=9090 \
    -e HOST=localhost \
    -e CLIENT_ID=test \
    -e CLIENT_SECRET=secret \
    -e CLIENT_REDIRECT_URI=http://localhost:8080/callback \
    -e CLIENT_LOGOUT_REDIRECT_URI=http://localhost:8080 \
    quay.io/appvia/mock-oidc-user-server:v0.0.2
```

Then run the example:

```console
python examples/generic.py
```

You should be able to visit `http://localhost:8080/login` and the mock OIDC server should pass your username to the resulting callback correctly.

I hope this helps.

Please let me know if I may close the issue.
