### ISSUE TITLE
redirect_url is set from request header

### ISSUE THREAD

**Issue by maru0123-2004** [tomasvotava/fastapi-sso#23]
In `process_login()`, now using `current_path` as `redirect_url` on this library, I think.   
`current_path` is this:
```python
current_path = f"{scheme}://{url.netloc}{url.path}"
```
scheme is...
```python
url = request.url
scheme = url.scheme
```
It is not bad for nomal usage.But I was stupidly used with apache web server's https proxy.
Then, in Request, there are "http" scheme. But in browser(and from google) "https" scheme.
And also, API Key was for "https", too...
So, I saw this error:
```
oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error: (redirect_uri_mismatch) Bad Request
```
This is just my fail episode, but it may be cause security issue or many problem like me. So, I make issue.

I'm very sorry for my bad English.
And I apologize in advance for being rude...
Thnk you.

**Comment by maru0123-2004** [comment]
I open PL to fix this issue.

**Comment by greenjellygit** [comment]
I totally agree with the @maru0123-2004, suggested PR is ok. In my situation where redirect_uri is pointed to my frontend app, the library is not able to get access_token because it builds a new redirect_uri based on the backend address inside `process_login`.
