### ISSUE TITLE
Arbitrary SSO error

### ISSUE THREAD

**Issue by pausanchezv** [tomasvotava/fastapi-sso#3]
Hello, I've using this SSO for a week now and I often run into this error
`Google callback error (401, "'state' parameter in callback request does not match our internal 'state', someone may be trying to do something bad.")`
The only way to make the sso work again is by changing the oauth2 credentials on google. I had to set like 4 new pairs and I am afraid of releasing the website because my users will run into the same error for sure, and the SSO will fail for them as well.

Am I missing anything here?

It's weird because the login works well and then, suddenly, it starts returning this error and there is no way to make it work without a new pair of credentials.

Thanks.

**Comment by pausanchezv** [comment]
To provide you with more context, it fails when I have been using it on a normal browser window and then I try to use it, for instance, in an incognito window. It will work on the first window, but it will strangely fail when using the incognito one.

**Comment by tomasvotava** [comment]
@pausanchezv Hi, thanks for reporting this.

Is it possible that you create initial login request from different domain than the callback uri? Such as `localhost/auth/login` -> `127.0.0.1/auth/callback`. This would mean the browser does not delete our `state` cookie.

**Comment by tomasvotava** [comment]
@pausanchezv I just published `fastapi-sso` version `0.2.10` with parameter `use_state`. You can see usage [here](https://github.com/tomasvotava/fastapi-sso#state). Hope this helps, please let me know so we may close this issue.

Note: If you use `poetry` you may need to clear your cache so it find the new `0.2.10` on PyPi.

**Comment by pausanchezv** [comment]
Thanks for the rapid answer. I'll let you know if I find more issues, for now with the new version 0.2.10 it looks like it's working well. I'll let you know if I have more issues. The library itself is really good! :)

**Comment by pausanchezv** [comment]
> @pausanchezv Hi, thanks for reporting this.
> 
> Is it possible that you create initial login request from different domain than the callback uri? Such as `localhost/auth/login` -> `127.0.0.1/auth/callback`. This would mean the browser does not delete our `state` cookie.

Yes. The domains are different because it is a static website in which app.website.com calls api.website.com, that kind of thing... So yes, request and callback are not the same.

**Comment by tomasvotava** [comment]
Thanks for feedback, I am happy the library serves its purpose 👌

Problem with incognito mode in browsers is that they block 3rd-party cookies, meaning they strictly separate between `app.website.com` and `api.website.com` and do not share their cookies among them. This way when you generate login request from `app.website.com`, cookie with `state` is saved for `app.website.com` and `api.website.com` does not see it once it gets the callback. I'd say I either need to store the `state` somewhere else or not use it at all, TBH I am not sure if that's ok from security's point of view.

Can we close this for now as there is now a workaround?

**Comment by pausanchezv** [comment]
Yeah sure I'll close it! Thanks for the answers!
