### ISSUE TITLE
Okta "invalid 'state' parameter" error 

### ISSUE THREAD

**Issue by delgado-jacob** [tomasvotava/fastapi-sso#36]
With the `use_state` change in the 0.6.4 release, the generic provider we've been using with Okta OIDC longer works. The provider returns a `the authentication request has an invalid 'state' parameter` error (Okta [requires](https://developer.okta.com/docs/reference/api/oidc/#parameter-detail) the state parameter). Setting `use_state=True` does not resolve the issue. I think I could workaround by implementing my own state parameter tracking, but is there a reason the state management has been removed altogether rather than just defaulting to False?

**Comment by tomasvotava** [comment]
Hi @delgado-jacob  and sorry for introducing breaking changes for you. This module is in early stages and the API may change from time to time, until it's stable and good enough to release it as `1.0.0`. I really believe in what was said in #34, not only was `use_state=True` a bad default but also I believe the SSO class shouldn't be responsible for checking the state for you. If you want to use the state, you may send it in `get_login_redirect`, e.g.:

```python
from uuid import uuid4

async def login():
    return await sso.get_login_redirect(state=uuid4().hex)
```

What is a good point, you may probably want to use the legacy `use_state`  parameter to indicate you want to send **some** `state` and you don't care about the value in which case `SSOBase` would generate a random `state` when requesting the login url but would not store the state nor check its value afterwards. I'll add this in a bit.

**Comment by delgado-jacob** [comment]
Thanks for the response, @tomasvotava. I would offer that setting the state value in a cookie and validating it on the provider response is a reasonable (optional) approach and I can attest (contrary to the claim in https://github.com/tomasvotava/fastapi-sso/issues/34) that it works perfectly well in a larger multi-server implementation. It's your prerogative to remove whatever you want, obviously, but I found it helpful functionality to have within the library.

**Comment by tomasvotava** [comment]
I haven't yet removed the functionality, it seems this issue is stale, thanks for this, if you'd ever wanted to discuss this further, let's reopen it.
