### ISSUE TITLE
[Question] where can i find the client id and secret in my provider?

### ISSUE THREAD

**Issue by codebydant** [tomasvotava/fastapi-sso#37]
Hi @tomasvotava,

Thanks for this wonderful tool. I was wondering where I can find the specific parameters from my provider, e.g GitHub or Microsoft since this is not mentioned in the docs.

**Comment by tomasvotava** [comment]
Hi, thanks a lot!

Each login provider would have a documentation describing how to get your client credentials. Look for something like `create oauth app`, e.g.:

- [Github](https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app)
- [Microsoft](https://learn.microsoft.com/en-us/azure/active-directory/saas-apps/openidoauth-tutorial)
- [Google](https://developers.google.com/identity/sign-in/web/sign-in#create_authorization_credentials)
