### ISSUE TITLE
Social Providers

### ISSUE THREAD

**Issue by pausanchezv** [tomasvotava/fastapi-sso#4]
Hi! I'm using this SSO and I gotta say I'm really happy with it. It works really well. However I kind of miss being able to sign up with Linkedin and Twitter. Are you planning to add them?

As I said I'm really happy with the SOO, this is the website on which I have used it!
[https://app.useofenglishpro.com/](https://app.useofenglishpro.com/)

Although that's not an issue I had to write the question here because I had nowhere to do so.

Thanks.

**Comment by tomasvotava** [comment]
Hi, I am sorry for the delay but there've been lots of stuff going on in work lately and I can not prioritize this. I am open to PRs and will come back to this once things settle a bit.

**Comment by pausanchezv** [comment]
> Hi, I am sorry for the delay but there've been lots of stuff going on in work lately and I can not prioritize this. I am open to PRs and will come back to this once things settle a bit.

Sure no problem! It was only a nice-to-have. The SSO works really well anyway. I'll just let you know if there's any bugs! Regarding the open PR, it's cool I'll look into it when I have some spare time!

**Comment by tomasvotava** [comment]
Just letting you know that I have finally created [CONTRIBUTING.md](https://github.com/tomasvotava/fastapi-sso/blob/master/CONTRIBUTING.md) as a guide to make your code ready for PR, in case you would still be interested in extending fastapi-sso's range of supported social providers.

**Comment by tomasvotava** [comment]
There hasn't been much going on about this, I may be adding LinkedIn or Twitter in the future. Also, the new Generic class was created, closing this for now.
