### ISSUE TITLE
use_state deprecation question

### ISSUE THREAD

**Issue by pausanchezv** [tomasvotava/fastapi-sso#40]
Hello, the new version says:

```Deprecation Warning: legacy use_state argument in SSOBase constructor is deprecated and will be removed.```

**What do I use if I wanna upgrade to the latest version?**

I have both looking like this right now:

```
google_sso = GoogleSSO(
    settings.google_client_id,
    settings.google_client_secret,
    settings.google_login_callback,
    use_state=False
)
facebook_sso = FacebookSSO(
    settings.facebook_client_id,
    settings.facebook_client_secret,
    settings.facebook_login_callback,
    use_state=False
)
```

The use_state is so useful to me, otherwise it fails when you logging in from different browsers. That use_state saved my life back in the day when you added it.

Thanks

**Comment by tomasvotava** [comment]
Hi @pausanchezv, there was a discussion about this in a PR. I understand there are people depending on this functionality, but I don't believe it should be a direct responsibility of the `SSOBase` class to deal with this. You can always use `state` argument when calling `get_login_url` to make sure your app works with login provider that requires `state` query parameter. Or do you actually need `SSOBase` to verify for you that the `state` that was sent to Google when requesting login url is the same when verifying the login?

**Comment by pausanchezv** [comment]
Ok so I see in your code that state is str | None. 
```
async def get_login_redirect(
        self,
        *,
        redirect_uri: Optional[str] = None,
        params: Optional[Dict[str, Any]] = None,
        state: Optional[str] = None,
    ) -> RedirectResponse:
```

An this is how I use it:
```
@router.get("/google", status_code=status.HTTP_303_SEE_OTHER)
async def google_authentication():
    """
    Google authentication
    """
    return await AuthController.google_sso.get_login_redirect()
```

So, what should I pass as a parameter to this function? I assume ```state=False```.

Can you confirm, please? The goal is to achieve the same I could do when I did this:
```
google_sso = GoogleSSO(
    settings.google_client_id,
    settings.google_client_secret,
    settings.google_login_callback,
    use_state=False
)
```

Thank you so very much.

**Comment by tomasvotava** [comment]
If you don't want to deal with the state at all, you should just be able not to pass anything, or am I missing something?

**Comment by pausanchezv** [comment]
Ok, I'll try. Gonna close the issue and open another one in case there are errors. Thanks for the library, I've been using it for almost 2 years now and it's just great!
