### ISSUE TITLE
User image too small

### ISSUE THREAD

**Issue by pausanchezv** [tomasvotava/fastapi-sso#41]
Hello!

Is there a way to tell the library to return a bigger user image? It's terribly small and it looks pretty bad on the profile page where I need images to be at least 300x300px more or less...

Thank you!

**Comment by tomasvotava** [comment]
Hi @pausanchezv, every provider returns, if any, a picture it deems appropriate. Which are you trying to use? Google?

**Comment by tomasvotava** [comment]
If so, you should be able to alter the picture url's parameter `s` (short for `size`, I guess) to select the width of the image that suits you.

**Comment by pausanchezv** [comment]
OK, how can I tell the library to do it for me? Otherwise, I have to do in code which is pretty messy. I mean I'll do it if necessary but if there'a a way to tell it to the library, even better.
Thanks!
