### ISSUE TITLE
SSO Google Change CODE for Token

### ISSUE THREAD

**Issue by kazuyabr** [tomasvotava/fastapi-sso#42]
Hi guys, How can we change code for token with this plugin?
I trying any methods, but I cant understand how I do this without import others packages like google-api-python-client google-auth-httplib2 google-auth-oauthlib

**Comment by tomasvotava** [comment]
Hi @kazuyabr, sorry if I'm getting this wrong, but if you only need access or refresh tokens, you can access them **after** `verify_and_process` has been called on the `SSO` instance:

```python
@app.get("/auth/callback")
async def auth_callback(request: Request):
    """Verify login"""
    sso = GoogleSSO(...)
    user = await sso.verify_and_process(request)
    # You wouldn't probably print the tokens, but:
    print(sso.access_token, sso.refresh_token)
```

**Comment by kazuyabr** [comment]
I will check it. thanks for help =D

**Comment by tomasvotava** [comment]
Hi @kazuyabr, did you get it to work? Can we close this issue for now?

**Comment by kazuyabr** [comment]
not, I try this

@router.get("/callback")
async def google_callback(request: Request):
    """Verify login"""
    sso = GoogleSSO(...)
    """Process login response from Google and return user info"""
    with google_sso:
        user = await google_sso.verify_and_process(request)
    print(sso.access_token, sso.refresh_token)
    return {
        "id": user.id,
        "picture": user.picture,
        "display_name": user.display_name,
        "email": user.email,
        "provider": user.provider,
    }
    
    But I cant see convertion CODE to Token in print.

**Comment by kazuyabr** [comment]
yeah, work =D thx and you can close this issue.
