### ISSUE TITLE
GitHub SSO returns null email if in GitHub's profile the email is private 

### ISSUE THREAD

**Issue by Cereal84** [tomasvotava/fastapi-sso#54]
If the user has set the email as private in its GitHub profile than the GitHub SSO class returns an empty email.
In order to retrieve the email even if it is private the class need to use 'https://api.github.com/user/emails"' endpoint.

That endpoint returns a list of email like
`
[
  {
    "email": "octocat@github.com",
    "primary": true,
    "verified": true,
    "visibility": "private"
  },
  {
    "email": "xxxxx@github.com",
    "primary": false,
    "verified": true,
    "visibility": "private"
  },
]
`
we're interested in the one with 'primary: true' value.

**Comment by Cereal84** [comment]
PR #55

**Comment by tomasvotava** [comment]
@Cereal84 I know it took long, but in the end I found out there was actually a bug in my passing the session on to `openid_from_response` method 🤦 the session was not only closed but it also wasn't authenticated properly. It should be working now, I will release 0.9.0 ASAP.

I have to close #69, though. I will mention you in the release at least, I am so sorry for how I resolved this in the end.

**Comment by Cereal84** [comment]
@tomasvotava Don't worry, the important thing is to have resolved it :).

I hope you have a nice day.
