### ISSUE TITLE
Minor error in fastapi security example.

### ISSUE THREAD

**Issue by AaronNHart** [tomasvotava/fastapi-sso#82]
First, thanks for developing this package, it's super handy and saved some time already. 

Regarding the import on line 5 here:
https://tomasvotava.github.io/fastapi-sso/how-to-guides/use-with-fastapi-security/

This:
from fastapi_sso import OpenID, GoogleSSO 

Should be:
from fastapi_sso.sso.google import GoogleSSO 
from fastapi_sso.sso.base import OpenID 

Thanks again!

**Comment by tomasvotava** [comment]
Hi @AaronNHart, thanks for raising this issue 🙏 
I added some import shortcuts in the [latest commit](https://github.com/tomasvotava/fastapi-sso/commit/321c651bc3d979c13e9ba93710fe70fa4938b42d#diff-28f028c1ed46143185e3cef55e73dcb4c9b6fe677b1b76d12c72e8a5723192e2), but seeing that this is not released yet, it only makes sense to make the docs work with what the users actually see, I'll address this ASAP.

**Comment by AaronNHart** [comment]
My pleasure, and thanks!
